const BlogData = [
    {
        "name": "Chicken Menu",
        "title": "Chicken Curry",
        "shortDescription": "This Chicken Curry Is Weeknight Dinner Goals.",
        "price": "350",
        "foodCategory": "Chicken",
        "type": "HomeMenu",
        "foodInstructions": ["Sprinkle the chicken evenly with 3/4 teaspoon salt, 1/4 teaspoon pepper and 1 teaspoon curry powder.", "Heat 1-1/2 tablespoons of oil in a 12-inch skillet over high heat until just smoking. Add the chicken in a single layer and cook, stirring occasionally, until lightly browned but still pink in spots, about 3 minutes. Transfer the partially cooked chicken to a clean bowl and set aside.", "Add the remaining 1-1/2 tablespoons oil to the skillet and set heat to medium. Add the onions and cook, stirring occasionally, until softened, about 5 minutes. Stir in the garlic, ginger and remaining 1-1/2 teaspoons curry powder and cook until fragrant, about a minute more.", "Whisk the chicken broth and cornstarch together to dissolve the cornstarch, then add to the skillet along with the sugar and 1/8 teaspoon salt. Bring to a boil, then reduce the heat to medium and cook until the sauce is nicely thickened, about 5 minutes.", "Add the peas and partially cooked chicken to the skillet, turn the heat down to low and simmer until the chicken is cooked through, a few minutes. Off the heat, stir in the yogurt and cilantro; then season with salt and pepper, to taste. Serve with basmati rice."],
        "ingredient": ["1-1/4 pounds boneless, skinless chicken breasts, cut into 1/4-inch strips.", "Salt and freshly ground black pepper.", "2-1/2 teaspoons curry powder, divided.", "3 tablespoons vegetable oil, divided.", "1 medium yellow onion, finely chopped.", "4 garlic cloves, minced.", "1 tablespoon grated fresh ginger.", "2 cups low sodium chicken broth, best quality such as Swanson.", "1 tablespoon cornstarch.", "2 teaspoons sugar.", "1 cup frozen peas (no need to thaw).", "1/4 cup plain low fat (2%) or whole Greek yogurt (do not use nonfat).", "1/4 cup chopped fresh cilantro.", "1 tablespoon butter.", "Water As required."],
        "tags": "Chicken Curry, Chicken Masalla.",
        "readyTime": "40 Minutes",
        "prepTime": "20 Minutes",
        "cookTime": "20 Minutes",
        "rating": "4.8",
        "servings": "4",
        "makingPic1": "https://i.ibb.co/D7MmSZb/Chicken-Curry-2.jpg",
        "makingPic2": "https://i.ibb.co/cC42f28/Chicken-Curry-3.jpg",
        "makingPic3": "https://i.ibb.co/5jWshYT/Chicken-Curry-5.webp"
    },
    {
        "name": "Pizza",
        "title": "Yummy Pizza",
        "shortDescription": "This is an excellent option for a starter, or as a Yummy Pizza!",
        "price": "180",
        "foodCategory": "Pizza",
        "type": "HomeMenu",
        "foodInstructions": ["Take a dough kneading plate and add all-purpose flour to it. Next, add salt and baking powder in it and sieve the flour once. Then, make a well in the centre and add 1 teaspoon of oil to it. On the other hand, take a little warm water and mix the yeast in it along with 1 teaspoon of sugar. Mix well and keep aside for 10-15 minutes. The yeast will rise in the meantime. Once the yeast has risen, add it to the flour knead the dough nicely using some water. Keep this dough aside for 4-6 hours. Then knead the dough once again. Now, the pizza dough is ready.", "Preheat the oven at 180 degree Celsius. Now, is the time to make the pizza base when the dough is ready. Dust the space a little using dry flour and take a large amount of the pizza dough. Using a rolling pin, roll this dough into a nice circular base. (Note: Make sure that the circular base is even at all ends.) Once you have made the base, use a fork and prick the base with it so that the base doesn't rise and gets baked nicely. Put it into the preheated oven and bake it 10 minutes. Now, your pizza base is ready.", "Now, wash the capsicum and slice it thinly in a bowl. Then, peel the onions and cut thin slices of it as well in another bowl. And finally, cut tomatoes and mushrooms in the same manner. However, make sure that those tomatoes have less juice in them. Once all the veggies are done, Now, grate the processed and mozzarella cheese in separate bowls.", "Then, take the fresh pizza base and apply tomato ketchup all over. Spread half the processed cheese all over the base and evenly put the veggies all across the base. Once you have put all the veggies, put a thick layer of mozzarella cheese.", "Put this pizza base in a baking tray and place it inside the oven. Let the pizza bake 10 minutes at 250 degree Celsius. Once done, take out the baking tray and slice the pizza. Sprinkle oregano and chilli flakes as per your taste and serve hot. (Note: Make sure that the oven is preheated at 250 degree Celsius for 5 minutes at least.)"],
        "ingredient": ["4 cup all purpose flour.", "1 cup mozzarella.", "3/4 cup and 1 and 1/4 tablespoon tomato ketchup.", "2 tomato.", "4 onion.", "2 teaspoon chilli flakes.", "2 teaspoon baking powder.", "2 teaspoon sugar.", "3/4 cup and 3 and 3/4 tablespoon processed cheese.", "8 mushroom.", "1 capsicum (green pepper).", "2 teaspoon oregano.", "2 tablespoon dry yeast.", "Butter.", "Water As required."],
        "tags": "Pizza, Yummy Pizza.",
        "readyTime": "30 Minutes",
        "prepTime": "10 Minutes",
        "cookTime": "20 Minutes",
        "rating": "5",
        "servings": "4",
        "makingPic1": "https://i.ibb.co/72q37jY/Pizza-1.webp",
        "makingPic2": "https://i.ibb.co/thytDBj/Pizza-2.jpg",
        "makingPic3": "https://i.ibb.co/4TpyrDn/Pizza-3.jpg"
    },
    {
        "name": "Pasta",
        "title": "Mexican Pasta",
        "shortDescription": "This Mexican Pasta recipe is absolutely bursting with your favorites.",
        "price": "120",
        "foodCategory": "Pasta",
        "type": "HomeMenu",
        "foodInstructions": ["In large, deep skillet with a lid (or a dutch oven), heat olive oil over medium-high heat. Once the oil is hot but not yet smoking, add the ground chicken, onion, and red and green bell peppers.", "Brown the meat, breaking it apart with a spoon, until it is fully cooked through and the onions are translucent, about 8 minutes.", "Add the garlic, chili powder, cumin, oregano, salt, and pepper and cook just until the garlic is fragrant, about 30 seconds. Add the water, salsa, tomato sauce, pasta, and beans.", "Reduce the heat to medium low, then cover the pan. Let simmer gently, stirring occasionally, just until the pasta is al dente and most of the liquid is absorbed (more liquid will absorb as it cools), about 12 to 15 minutes. As you stir the pasta while it cooks, check to make sure it's not becoming dry. If it is, stir in water as needed to keep it moist and simmering.", "Remove the pan from the heat and stir in half of the cheese, then sprinkle the remaining cheese on top. Serve hot with any of your favorite toppings."],
        "ingredient": ["1 cup Cheddar cheese.", "1 cup Monterey Jack Cheese.", "4 oz. Velveeta cheese, cut into cubes (equal to 1/3 cup)* can sub with ¾ cup shredded cheese.", "1 lb. Ground Mutton.", "1 Tablespoon Butter.", "2 cloves Garlic.", "1 oz. packet Taco Seasoning.", "1 Tablespoon Worcestershire sauce.", "2 Tablespoons Tomato paste.", "1 cup mutton broth.", "1 cup Chicken broth.", "1 cup Whole milk, at room temp.", "1 cup Whole milk, at room temp.", "1 (10 oz.) can Rotel Tomatoes with green chilies, undrained", "1/2 lb. Medium pasta shells, see notes", "Water As required."],
        "tags": "Mexican Pasta, Pasta.",
        "readyTime": "45 Minutes",
        "prepTime": "10 Minutes",
        "cookTime": "35 Minutes",
        "rating": "4.8",
        "servings": "1",
        "makingPic1": "https://i.ibb.co/LPm6kVp/Maxican-pasta-1.jpg",
        "makingPic2": "https://i.ibb.co/10r0Bbp/Maxican-pasta-3.jpg",
        "makingPic3": "https://i.ibb.co/LnpLxYg/Maxican-pasta-4.gif"
    },
    {
        "name": "Burger",
        "title": "Chill & Hot Burger",
        "shortDescription": "Yummy, testy hot burger to italian flavors.",
        "price": "150",
        "foodCategory": "Burger",
        "type": "HomeMenu",
        "foodInstructions": ["In a bowl, mix ground beef, egg, onion, bread crumbs, Worcestershire, garlic, 1/2 teaspoon salt, and 1/4 teaspoon pepper until well blended. Divide mixture into four equal portions and shape each into a patty about 4 inches wide.", "Lay burgers on an oiled barbecue grill over a solid bed of hot coals or high heat on a gas grill (you can hold your hand at grill level only 2 to 3 seconds); close lid on gas grill.", "Cook burgers, turning once, until browned on both sides and no longer pink inside (cut to test), 7 to 8 minutes total. Remove from grill.", "Lay buns, cut side down, on grill and cook until lightly toasted, 30 seconds to 1 minute.", "Spread mayonnaise and ketchup on bun bottoms. Add lettuce, tomato, burger, onion, and salt and pepper to taste. Set bun tops in place."],
        "ingredient": ["1 pound ground lean (7% fat) chicken.", "1 large egg", "1/2 cup minced onion.", "1/2 cup fine dried bread crumbs.", "1 tablespoon Worcestershire.", "1 or 2 cloves garlic, peeled and minced.", "About 1/2 teaspoon salt.", "About 1/4 teaspoon pepper.", "4 hamburger buns (4 in. wide), split.", "About 1/4 cup mayonnaise.", "About 1/4 cup ketchup.", "4 iceberg lettuce leaves, rinsed and crisped.", "1 firm-ripe tomato, cored and thinly sliced.", "4 thin slices red onion", "Water As required."],
        "tags": "Hot Burger, Chill Burger, Burger.",
        "readyTime": "37 Minutes",
        "prepTime": "12 Minutes",
        "cookTime": "25 Minutes",
        "rating": "4.9",
        "servings": "1",
        "makingPic1": "https://i.ibb.co/YdZxJtj/Burger-1.jpg",
        "makingPic2": "https://i.ibb.co/k4pdL3S/Burger-2.jpg",
        "makingPic3": "https://i.ibb.co/zGRL9n8/Burger-5.jpg"
    },
    {
        "name": "Chicken And Rice",
        "title": "Chicken And Rice",
        "shortDescription": "This Chicken and Rice recipe has captured the hearts of people.",
        "price": "180",
        "foodCategory": "Chicken And Rice",
        "type": "HomeMenu",
        "foodInstructions": ["Preheat oven to 400˚F (200˚C). In a large bowl, evenly season chicken thighs with salt, pepper, paprika, and parsley. On high, heat olive oil in a oven-proof pot and place chicken thighs, skin-side down, in the hot oil. Cook 5-6 minutes or the thighs develop brown crispy skin and flip over.", "Cook an additional 5-6 minutes to brown the other side and remove from the pot. Add the garlic and onions to the pot, and cook until the onions are transparent.", "Pour in the rice and chicken broth to the pot and season with salt and pepper. Stir well, bringing to a boil.", "Add the chicken thighs back into the pot, skin-side up, on top of the rice, bring back to a boil and cover with a lid.", "Bake for 35-40 minutes, or until the rice is fully cooked. NOTE: For a crispy skin, remove chicken thighs and broil. Enjoy!"],
        "ingredient": ["5 chicken thighs.", "2 teaspoon salt.", "2 teaspoon pepper.", "3 teaspoon paprika.", "1 teaspoon dried parsley.", "4 tablespoon olive oil.", "1 tablespoon garlic, minced.", "1/2 cup red onion(75 g), diced.", "8 cup long grain rice(200 g).", "1 1/2 cups chicken broth(360 mL).", "salt, to taste.", "pepper, to taste.", "1/4 teaspoon green Chill", "1/2 cup butter, sliced into pats.", "Water As required."],
        "tags": "Chicken And Rice.",
        "readyTime": "50 Minutes",
        "prepTime": "15 Minutes",
        "cookTime": "35 Minutes",
        "rating": "4.6",
        "servings": "3",
        "makingPic1": "https://i.ibb.co/ZSxvgJS/Chicken-and-Rice-1.webp",
        "makingPic2": "https://i.ibb.co/RBCPSBG/Chicken-and-Rice-2.webp",
        "makingPic3": "https://i.ibb.co/cg6SrKL/Chicken-and-Rice-3.webp"
    },
    {
        "name": "Mutton Curry",
        "title": "Mutton Curry",
        "shortDescription": "Delicious, soft chunks of Indian style spiced onion tomato gravy.",
        "price": "220",
        "foodCategory": "Mutton Curry",
        "type": "HomeMenu",
        "foodInstructions": ["Here is an excellent mutton recipe that you can easily make at home. To prepare this easy recipe, firstly, clean and wash the mutton pieces. Next, put a large pan over medium flame and melt ghee in it. Once the ghee has melted, add cardamom, cloves, black peppercorns, cinnamon stick. Saute these for a minute and add the sliced onions along with salt in it. Saute till the onion turns light brown in colour. Next, add the ginger paste along with garlic paste and cook the mixture until the raw smell disappears.", "Now, add turmeric powder, red chilli powder and coriander powder to the fried onion and mix it well. Add the mashed tomatoes and mix them well with the other ingredients. Make sure the tomatoes turn pulpy and cook this mix until oil separates from the masala in the pan.", "Now, add mutton pieces to this masala and mix it well. Ensure that mutton pieces are evenly coated with the masala. Pour the yoghurt in the mutton masala and mix it well. Let it cook for 4-5 minutes and, then, add water to it. Stir it well and check the seasoning once. Then, add chopped coriander leaves along with garam masala powder. Give it a quick stir. Cook it for another 25 minutes to ensure that mutton is no longer raw and is perfectly juicy.", "Once done, take it off the flame and transfer the dish to a bowl. Serve it hot with rice or naan to enjoy!", "You can also garnish the dish with chopped green chillies and julienned ginger if you want. If you liked the recipe, make sure you rate it and leave a comment in the section below. Happy Cooking!"],
        "ingredient": ["500 gm mutton.", "2 tablespoon coriander powder.", "4 onion.", "2 teaspoon garlic paste.", "4 clove.", "5 green cardamom.", "1 cinnamon stick.", "salt as required.", "4 tablespoon ghee.", "1/2 cup yoghurt (curd).", "2 teaspoon ginger paste.", "2 teaspoon red chilli powder.", "3 tomato & 8 peppercorns.", "1 teaspoon garam masala powder.", "1/2 teaspoon turmeric."],
        "tags": "Mutton Curry, Curry, Mutton",
        "readyTime": "60 Minutes",
        "prepTime": "20 Minutes",
        "cookTime": "40 Minutes",
        "rating": "4.9",
        "servings": "2",
        "makingPic1": "https://i.ibb.co/X4Bg8hc/Mutton-curry-1.jpg",
        "makingPic2": "https://i.ibb.co/3s1dqSZ/Mutton-curry-2.jpg",
        "makingPic3": "https://i.ibb.co/WDHY3KG/Mutton-curry-3.jpg"
    }
]

export default BlogData